### ISSUE TITLE
support storybook 4 (5)

### ISSUE THREAD

**Issue by ilyaztsv** [pocka/storybook-addon-vue-info#62]
**Is your feature request related to a problem? Please describe.**

The current storybook version is 4. Also, the storybook team is planning to release version 5 (v5.0.0-alpha.1 is released already). Do you have a plan to support storybook v4 and v5?

**Comment by pocka** [comment]
Yes. I'm going to update dependencies in release/v1.0 branch.
But I think this addon will work well with storybook@4 (I'm not sure about v5...)

**Comment by ilyaztsv** [comment]
Thanks for the feedback!

Yes, the addon works fine with storybook@4.1.6

Also, I tried to use the addon with storybook@4.2.0-alpha.11 and it does not work :( You can see the error in the [following repo](https://github.com/ilyaztsv/storybook-addon-vue-info-and-storybook4alfa).

**Comment by jlpospisil** [comment]
@pocka Will the updates make it compatible with @storybook/addon-knobs?  Right now, knobs stop working when this decorator is added.

**Comment by noah004B** [comment]
I have the same issue. Knobs stop working with storybook@4.1.7

**Comment by pocka** [comment]
@jlpospisil  
What version of storybook are you using?

I think the problem with knobs addon is different from the one @ilyaztsv points out.
Should move it into another issue IMO.

**Comment by pocka** [comment]
# Bug details

When we use this addon with `.addDecorator` at storybook@4.2.0-alpha.XX, this addon throws an error.

```
`template` or `render` must be on component options, but got undefined.
```

After my quick search, https://github.com/storybooks/storybook/pull/5057 (storybook@4.2.0-alpha.6) changed behavior for decorators and causes the error.

## Confirmed versions

- storybook-addon-vue-info@1.0.0-alpha.0
- @storybook/vue@4.2.0-alpha.11

**Comment by pocka** [comment]
Fixed with @1.0.0-alpha.1 (Commit d11151d69988f3a0f192e04e9714e154578094a6)

**Comment by simezi** [comment]
Hi, @pocka 

I upgraded storybook@5.0.0 and encountered bug today.
```
ERR! Error: Cannot find module 'emotion-theming/package.json'
ERR!     at Function.Module._resolveFilename (module.js:538:15)
ERR!     at Function.resolve (internal/module.js:18:19)
ERR!     at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/ui/paths.js:16:38)
ERR!     at Module._compile (module.js:643:30)
ERR!     at Object.Module._extensions..js (module.js:654:10)
ERR!     at Module.load (module.js:556:32)
ERR!     at tryModuleLoad (module.js:499:12)
ERR!     at Function.Module._load (module.js:491:3)
ERR!     at Module.require (module.js:587:17)
ERR!     at require (internal/module.js:11:18)
ERR!     at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (module.js:643:30)
ERR!     at Object.Module._extensions..js (module.js:654:10)
ERR!     at Module.load (module.js:556:32)
ERR!     at tryModuleLoad (module.js:499:12)
ERR!     at Function.Module._load (module.js:491:3)
ERR!  { Error: Cannot find module 'emotion-theming/package.json'
ERR!     at Function.Module._resolveFilename (module.js:538:15)
ERR!     at Function.resolve (internal/module.js:18:19)
ERR!     at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/ui/paths.js:16:38)
ERR!     at Module._compile (module.js:643:30)
ERR!     at Object.Module._extensions..js (module.js:654:10)
ERR!     at Module.load (module.js:556:32)
ERR!     at tryModuleLoad (module.js:499:12)
ERR!     at Function.Module._load (module.js:491:3)
ERR!     at Module.require (module.js:587:17)
ERR!     at require (internal/module.js:11:18)
ERR!     at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (module.js:643:30)
ERR!     at Object.Module._extensions..js (module.js:654:10)
ERR!     at Module.load (module.js:556:32)
ERR!     at tryModuleLoad (module.js:499:12)
ERR!     at Function.Module._load (module.js:491:3)
ERR!   stack: 'Error: Cannot find module \'emotion-theming/package.json\'\n    at Function.Module._resolveFilename (module.js:538:15)\n    at Function.resolve (internal/module.js:18:19)\n    at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/ui/paths.js:16:38)\n    at Module._compile (module.js:643:30)\n    at Object.Module._extensions..js (module.js:654:10)\n    at Module.load (module.js:556:32)\n    at tryModuleLoad (module.js:499:12)\n    at Function.Module._load (module.js:491:3)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/yusukematsubara/src/github.com/baseinc/frontend-base-kit/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)\n    at Module._compile (module.js:643:30)\n    at Object.Module._extensions..js (module.js:654:10)\n    at Module.load (module.js:556:32)\n    at tryModuleLoad (module.js:499:12)\n    at Function.Module._load (module.js:491:3)',
ERR!   code: 'MODULE_NOT_FOUND' }
```

Perhaps this might be because `storybook-addon-vue-info` depends on old `@storybook/addons`.
As a workaround , I wrote `resolutions` as below and solved the problem

```
{
    "storybook-addon-vue-info/@storybook/addons":"^5.0.0"
} 
```

Could you update dependency for next version of `storybook-addon-vue-info`


Thanks in advance.

**Comment by pocka** [comment]
@simezi I've published `1.0.0-beta.1` which supports both storybook@4.x and storybook@5.0 (https://github.com/pocka/storybook-addon-vue-info/commit/4dd389f76639cbbd6a0629000b6949c045543642). This version depends on `@storybook/addons` as `peerDependencies` so it will use your installed version of the package.

**Comment by simezi** [comment]
@pocka 
I appreciate your kindness and quick release. ❤️

**Comment by immarina** [comment]
@pocka Thanks for the update, but somehow `1.0.0-beta.1` doesn't seem to be working with `5.0`. Is there any particular configuration changes that we need to apply other than the ones on the migration guide? I'm getting a blank screen on every story that uses the addon, plus `:key` error warnings from vue.

**Comment by pocka** [comment]
@immarina 
> Is there any particular configuration changes that we need to apply other than the ones on the migration guide? 

To migrate from `storybook-addon-vue-info@0.x`, you need to:
- Change `withInfo()(() => /* your story */)` to [`.addDecorator(withInfo)` & Story parameter](https://github.com/pocka/storybook-addon-vue-info#usage)
- Register the addon in `.storybook/addons.js` (described in new [Getting started](https://github.com/pocka/storybook-addon-vue-info#getting-started) section)
- Add our docgen loader (OPTIONAL but recommended)

There should be no changes required for the Storybook side to use the addon.

> plus :key error warnings from vue.

hmm... I noticed React complains no "key" props thing, but Vue didn't.

**Comment by immarina** [comment]
@pocka Hey so i tried everything you said again.
* Changed all `.addDecorator` calls to use `import { withInfo } from 'storybook-addon-vue-info'`
* Registered the addon in addons.js `import 'storybook-addon-vue-info/lib/register'`
* Added the loader: (Do i need to add the styleguidest package?)
``` 
config.module.rules.push({
        test: /\.vue$/,
        loader: 'storybook-addon-vue-info/loader',
        enforce: 'post'
    })
```

However im getting a working storybook but all the Vue info screens are blank.
Im getting only two errors on console, the :key error for React and: `onStory(...) has been replaced with on(STORY_CHANGED, ...)`

Any suggestions?

**Comment by dartist21** [comment]
@pocka 

> NOTE: info option is required for the addon. If you omit it, it won't work.

Can we omit somehow in future releases? Not very comfortable to use, since a description is not always needed

**Comment by pocka** [comment]
@dartist21 
Do you mean "display info without `info` parameter"? It's by design, to enable users to turn on/off the addon per story. You can write `info: true` or `info: {}` when you don't need summary texts.

**Comment by pocka** [comment]
If you have any problems related to SB4/5 or usage questions about 1.0 version, please open a new issue.
